# Generated by Django 3.1.4 on 2021-01-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='title',
            new_name='album_title',
        ),
    ]
