# Generated by Django 3.1.4 on 2021-02-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20210116_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='len',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
